//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBNSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Client
    {
        public int ClientId { get; set; }
        [Required(ErrorMessage ="Name cannot be blank")]
        public string Name { get; set; }
        [Required(ErrorMessage ="Select a proper status")]
        public int Status { get; set; }
        public string PANNo { get; set; }
        public Nullable<int> AssignedStaffHrid { get; set; }
        public string SBId { get; set; }
        public Nullable<bool> SBVPN { get; set; }
        public string SMSId { get; set; }
        public Nullable<bool> UsesATM { get; set; }
    
        public virtual ClientsBranch ClientsBranch { get; set; }
    }
}
