//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBNSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.ClientsBranches = new HashSet<ClientsBranch>();
        }
    
        public int ClientId { get; set; }
        public string Name { get; set; }
        public int Status { get; set; }
        public string PANNo { get; set; }
        public Nullable<int> AssignedStaffHrid { get; set; }
        public string SBId { get; set; }
        public Nullable<bool> SBVPN { get; set; }
        public string SMSId { get; set; }
        public Nullable<bool> UsesATM { get; set; }
    
        public virtual ClientsBranch ClientsBranch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientsBranch> ClientsBranches { get; set; }
    }
}
