//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBNSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientsContact
    {
        public int ClientContactId { get; set; }
        public int BranchId { get; set; }
        public string Name { get; set; }
        public string MobileNo { get; set; }
        public string EmailId { get; set; }
        public string OfficeExt { get; set; }
        public string Department { get; set; }
        public string Designation { get; set; }
    
        public virtual ClientsBranch ClientsBranch { get; set; }
    }
}
