//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBNSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserValidationRequest
    {
        public int Recid { get; set; }
        public int ValidationType { get; set; }
        public int UserId { get; set; }
        public System.DateTime ValidationExpiryDate { get; set; }
        public string ValidationKey { get; set; }
        public string ValidationPin { get; set; }
        public Nullable<int> ValidationStatus { get; set; }
    
        public virtual Users User { get; set; }
    }
}
